version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: |
          echo -e "$GPG_KEY" | gpg --import
          mvn -e -s .circleci/settings.xml clean compile verify
  site:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: |
          echo -e "$GPG_KEY" | gpg --import
          mvn -e -s .circleci/settings.xml -DskipTests clean compile site:site site:stage site:deploy
  deploy:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: |
          echo -e "$GPG_KEY" | gpg --import
          mvn -e -s .circleci/settings.xml -DskipTests clean compile deploy
  release:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: |
          echo -e "$GPG_KEY" | gpg --import
          mvn -e -s .circleci/settings.xml -DskipTests --batch release:clean release:prepare release:perform

workflows:
  version: 2.0
  do_everything:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
                - mvn-repo
      - site:
          requires:
            - test
          filters:
            branches:
              ignore:
                - gh-pages
                - mvn-repo
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore:
                - gh-pages
                - mvn-repo
      - release:
          requires:
            - test
          filters:
            branches:
              ignore:
                - gh-pages
                - mvn-repo

